site_name: Teste de Ferramentas
repo_url: https://github.com/rib-thiago/tools
repo_name: rib-thiago/tools
edit_uri: /tree/main/docs


theme:
  name: material
  language: pt-BR

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]
